# Generated by Django 4.2.6 on 2023-11-20 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiefDataOfficers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('full_name', models.CharField(help_text='Şəxsin ad, soyadını bütöv şəkildə daxil edin.', max_length=50, verbose_name='Şirkət rəhbərinin ad, soyadı')),
                ('image', models.FileField(unique=True, upload_to='CDOs/', verbose_name='Şirkət rəhbərinin fotosu')),
                ('position', models.CharField(max_length=200, verbose_name='Şirkət rəhbərinin vəzifəsi')),
                ('company', models.CharField(max_length=200, verbose_name='Çalışdığı şirkətin adı')),
                ('linkedin_url', models.URLField(unique=True, verbose_name='Şirkət rəhbərinin linkedin profil linki')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Şirkət rəhbəri',
                'verbose_name_plural': 'Şirkət rəhbərləri',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='community_c_publish_49a4ba_idx')],
            },
        ),
    ]
