# Generated by Django 4.2.6 on 2023-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chiefdataofficers',
            name='full_name',
        ),
        migrations.AddField(
            model_name='chiefdataofficers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirkət rəhbərinin adı'),
        ),
        migrations.AddField(
            model_name='chiefdataofficers',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şirkət rəhbərinin soyadı'),
        ),
    ]
