# Generated by Django 4.2.6 on 2023-11-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_chiefdataofficers_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentpool',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='talentpool',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Soyadı'),
        ),
    ]
