# Generated by Django 4.2.6 on 2023-11-24 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_talentpool_name_alter_talentpool_surname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talentpool',
            options={'ordering': ['-published_at'], 'verbose_name': 'Talant mərkəzi'},
        ),
    ]
