# Generated by Django 4.2.6 on 2023-11-24 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_talentpool_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('sector_name', models.CharField(max_length=50, verbose_name='Sector dı')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Talant sectorları',
                'ordering': ['sector_name'],
            },
        ),
        migrations.AddField(
            model_name='talentpool',
            name='sector',
            field=models.ManyToManyField(related_name='talent_pool', to='community.talentsector'),
        ),
    ]
