# Generated by Django 4.2.6 on 2023-11-24 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_talentsector_talentpool_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('position_name', models.CharField(max_length=50, verbose_name='Vəzifə')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Talantın vəzifəsi',
                'verbose_name_plural': 'Talant vəzifələri',
                'ordering': ['position_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='talentpool',
            options={'ordering': ['-published_at'], 'verbose_name': 'Talant mərkəzi', 'verbose_name_plural': 'Talant mərkəzləri'},
        ),
        migrations.AlterModelOptions(
            name='talentsector',
            options={'ordering': ['sector_name'], 'verbose_name': 'Talant sektoru', 'verbose_name_plural': 'Talant sektorları'},
        ),
        migrations.RemoveField(
            model_name='talentpool',
            name='position',
        ),
        migrations.AlterField(
            model_name='talentpool',
            name='sector',
            field=models.ManyToManyField(related_name='talent_pool', to='community.talentsector', verbose_name='Sektor'),
        ),
        migrations.AlterField(
            model_name='talentsector',
            name='sector_name',
            field=models.CharField(max_length=50, verbose_name='Sector adı'),
        ),
        migrations.AddField(
            model_name='talentpool',
            name='position',
            field=models.ManyToManyField(related_name='talent_pool', to='community.talentposition', verbose_name='Vəzifə'),
        ),
    ]
