# Generated by Django 4.2.6 on 2023-11-24 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_talentposition_alter_talentpool_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə edilmə tarixi')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nəşr tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('level_name', models.CharField(max_length=50, verbose_name='Səviyyə')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Talant işinin səviyyəsi',
                'verbose_name_plural': 'Talant işinin səviyyələri',
                'ordering': ['level_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='talentpool',
            options={'ordering': ['-published_at'], 'verbose_name': 'Talant', 'verbose_name_plural': 'Talantlar'},
        ),
    ]
