# Generated by Django 4.2.6 on 2023-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_talentlevel_alter_talentpool_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpool',
            name='level',
            field=models.ManyToManyField(related_name='talent_pool', to='community.talentlevel', verbose_name='gördüyü işin səviyyəsi'),
        ),
    ]
