# Generated by Django 4.2.6 on 2023-11-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_alter_talentpool_work_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentpool',
            name='position',
        ),
        migrations.AddField(
            model_name='talentpool',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_pool', to='community.talentposition', verbose_name='Vəzifə'),
        ),
    ]
