# Generated by Django 4.2.6 on 2023-11-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_remove_talentpool_position_talentpool_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentpool',
            name='level',
        ),
        migrations.RemoveField(
            model_name='talentpool',
            name='sector',
        ),
        migrations.AddField(
            model_name='talentpool',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_pool', to='community.talentlevel', verbose_name='gördüyü işin səviyyəsi'),
        ),
        migrations.AddField(
            model_name='talentpool',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_pool', to='community.talentsector', verbose_name='Sektor'),
        ),
    ]
