# Generated by Django 4.2.6 on 2023-11-27 08:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_remove_talentpool_level_remove_talentpool_sector_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='talentlevel',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='talentposition',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='talentsector',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
