# Generated by Django 4.2.6 on 2023-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_alter_talentlevel_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiefdataofficers',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talentlevel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talentpool',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talentposition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='talentsector',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
